# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(db_index=True, max_length=4096),
        ),
    ]
