# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('base', '0002_auto_20160905_1913'),
	]

	operations = [
		migrations.CreateModel(
			name='Issue',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True,
					serialize=False, verbose_name='ID')),
				('file', models.CharField(max_length=4096)),
				('line', models.IntegerField()),
				('position', models.IntegerField()),
				('text', models.CharField(max_length=256)),
				('code', models.CharField(max_length=4096)),
				('project', models.ForeignKey(
					on_delete=django.db.models.deletion.CASCADE,
					to='base.Project')),
			],
		),
	]
