# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('base', '0003_project_repo_url'),
	]

	operations = [
		migrations.CreateModel(
			name='Object',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True,
					serialize=False, verbose_name='ID')),
				('oid', models.BigIntegerField(db_index=True)),
				('issues_count', models.IntegerField()),
				('project', models.ForeignKey(
					on_delete=django.db.models.deletion.CASCADE,
					to='base.Project')),
			],
		),
	]
